import { useMemo, useState } from 'react'
import { Filter, SlidersHorizontal } from 'lucide-react'
import PageHeader from '../../components/layout/PageHeader'
import SearchBar from '../../components/common/SearchBar'
import AlertTable from '../../components/alerts/AlertTable'
import { alerts } from '../../data/mockData'
import { useNavigate } from 'react-router-dom'

export default function Alerts() {
  const [query, setQuery] = useState('')
  const [severity, setSeverity] = useState('all')
  const navigate = useNavigate()

  const filtered = useMemo(() => alerts.filter((alert) => {
    const text = `${alert.type} ${alert.camera} ${alert.trackId}`.toLowerCase()
    return text.includes(query.toLowerCase()) && (severity === 'all' || alert.severity === severity)
  }), [query, severity])

  const review = (alert) => navigate(`/evidence?alert=${alert.id}`)

  return (
    <>
      <PageHeader title="Alerts" description="Review event candidates generated by the monitoring pipeline." />
      <div className="filter-bar">
        <SearchBar value={query} onChange={setQuery} placeholder="Search alerts, cameras or tracks..." />
        <div className="select-wrap"><SlidersHorizontal size={16} /><select value={severity} onChange={(e) => setSeverity(e.target.value)}><option value="all">All severities</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div>
        <button className="secondary-button"><Filter size={16} /> Filters</button>
      </div>
      <div className="panel">
        <div className="panel__header">
          <div><h2>Event candidates</h2><p>{filtered.length} records match the current view.</p></div>
        </div>
        <AlertTable alerts={filtered} onReview={review} />
      </div>
    </>
  )
}
